title: "ZHANG Panyu"
author: "ZHANG Panyu"
description: "ICLab@KAIST"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true #
show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
#minimal: true            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", file: "/assets/resume.pdf"}
  - {title: "Lab", url: "http://ic.kaist.ac.kr"}
  - {title: "Research", file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:panyu@kse.kaist.ac.kr"}
  - {title: Github, icon: github, url: "https://github.com/SteinPanyu"}
  - {title: Researchgate, icon: researchgate, url: "https://www.researchgate.net/profile/Panyu-Zhang-2"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/panyu-zhang-689a43178/"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
